name: CI/CD for Express and MongoDB

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - run: npm run build


  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=a0192340@141.8.195.218 "cd domains/goslink-messenger.online/public_html/api && git pull && npm install && npm run build"
          echo "Deployment completed."