name: CI/CD for Express and MongoDB

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - run: npm run build


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

#      - name: Deploy application
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
#            cd domains/goslink-messenger.online/public_html/api
#            git pull origin master
#            npm install
#            npm run build # Если ваше приложение требует сборки
#            pm2 restart all # или pm2 start app.js --name "your-app-name" если это новый запуск
#          EOF
